bazel-contrib/rules_distroless

apt/private/package_index.bzl

On Ubuntu 24.04, and likely other distributions  - a Package is able to be published to Ubuntu repositories with non-standard formatting.
Example (package `btm`): 
```
% grep 'pool/universe/b/btm/btm_0.9.6-4_amd64.deb' ~/Downloads/Packages\ 3 -A10 -B14
Package: btm
Architecture: amd64
Version: 0.9.6-4
Built-Using: rust-ahash-0.7 (= 0.7.7-2), rust-nix (= 0.26.2-1), rust-option-ext (= 0.2.0-1), rustc (= 1.75.0+dfsg0ubuntu1-0ubuntu1)
Multi-Arch: allowed
Priority: optional
Section: universe/utils
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Jonas Smedegaard <dr@jones.dk>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 4799
Depends: libc6 (>= 2.38), libgcc-s1 (>= 4.2)
Suggests: bash-completion
Filename: …
```

fix: improve parsing of Package.gz metadata, matching Debian parser logic

---

apt/private/package_index.bzl
examples/apt/bullseye.lock.json
examples/apt/bullseye.yaml

Willing to concede that this may just be my own PEBKAC, but after struggling to understand why one repository would work but another one would not - I discovered that there are assumptions made around the URL passed in the `sources` section of the YAML. Specifically, the assumption covered here is that the URL does _not_ end in a "/".
For most HTTP servers, they'll see a '//' and (more or less) understand what to do and redirect to the expected path. For some repositories, however, they parse these '//' as literal paths which return a 404 or otherwise non-2xx code with the contents of the file as expected.
```
$ git diff examples/apt/bullseye.yaml
diff --git a/examples/apt/bullseye.yaml b/examples/apt/bullseye.yaml
index 06afe45..4d0c786 100644
--- a/examples/apt/bullseye.yaml
+++ …
```

fix: trim trailing '/' on URL if provided in package YAML

---

apt/private/dpkg_status.bzl
apt/private/dpkg_statusd.bzl
apt/private/index.bzl
distroless/private/cacerts.bzl

I built an Ubuntu based image and ran into `control.tar.zst` and `data.tar.zst` files inside the `.debs`
This relatively minor patch adds support (`zstd` needs to be on `$PATH` for `bsdtar` to find it)
I have another branch with an `//examples/apt-ubuntu` copy that riffs on `//examples/apt` to test this with ... I could include it in examples if you'd like to have it around for testing, or leave it out like I've left this diff.

support zstd compressed {control,data}.tar files

---

apt/private/index.bzl
examples/apt/BUILD.bazel
examples/apt/bullseye.lock.json
examples/apt/bullseye.yaml
examples/apt/test_linux_amd64.yaml
examples/apt/test_linux_arm64.yaml

set package `:data` visibility to public so it can be used in a call to `cacerts()`
I stuck a quick check into `examples/apt` tests to verify that it behaves as expected.

fix package `:data` visibility so it's compatible with `cacerts()`

---

apt/extensions.bzl

This allows automatic population of `use_repo` statements.

Return extension_metadata from apt extension

---

apt/private/resolve.bzl

Currently having duplicate packages in your manifest will cause bad behavior when actually using those packages.
Fail when duplicate packages are seen in the manifest file.
Ex: 2 dpkg packages in packagesand `bazel run @bullseye//:lock`
```
packages:
- "dpkg"
- "dpkg"
```
Without changes and duplicates, the lock passes, but will have duplicate dependencies which leads to errors when actually using the package "@bullseye//dpkg".
```
{
"key": "libcrypt1_1-4.4.18-4_amd64",
"name": "libcrypt1",
"version": "1:4.4.18-4"
},
...
{
"key": "libcrypt1_1-4.4.18-4_amd64",
"name": "libcrypt1",
"version": "1:4.4.18-4"
},
```
```
ERROR: /home/eric/.cache/bazel/_bazel_eric/0dc37115db8d04cb9adf89231812a093/external/bullseye/dpkg/amd64/BUILD.bazel:18:10: Label '@bullseye//libcrypt1/amd64:amd64' is …
```

Fail on manifest duplicate packages

---

distroless/private/cacerts.bzl
distroless/private/tar.bzl
examples/cacerts/BUILD.bazel
examples/debian_snapshot/BUILD.bazel
examples/debian_snapshot/test_linux_amd64.yaml
examples/debian_snapshot/test_linux_arm64.yaml

The existing `cacert()` implementation builds the single bundle of certs in
`/etc/ssl/certs/ca-certifates.crt`. This isn't read by default, and results in
a verification error:
```shell
r00t@9c80da3575a7:~# echo | openssl s_client -connect www.google.com:443 2>&1 | grep Verify
Verify return code: 20 (unable to get local issuer certificate)
```
The default path for the single cert bundle is `/usr/lib/ssl/cert.pem`
```shell
r00t@9c80da3575a7:~# ln -sf /etc/ssl/certs/ca-certificates.crt /usr/lib/ssl/cert.pem
r00t@9c80da3575a7:~# echo | openssl s_client -connect www.google.com:443 2>&1 | grep Verify
Verify return code: 0 (ok)
```
So ship that symlink as part of `cacert()`

fix `cacert()` to work with openssl's defaults

---

MODULE.bazel.lock
e2e/smoke/BUILD
examples/debian_shared_dependencies/BUILD.bazel
examples/debian_shared_dependencies/bullseye.lock.json
examples/debian_snapshot/BUILD.bazel
examples/debian_snapshot/bullseye.lock.json
examples/ubuntu_snapshot/BUILD.bazel
examples/ubuntu_snapshot/noble.lock.json

[ci: update ci and exclude windows (#82)](https://github.com/GoogleContainerTools/rules_distroless/commit/7cb92b772a54346fe3f314110ee767230a4f1b00) added `target_compatible_with` arguments to some of the tests restricting them to linux but it also forced amd64 instead of allowing the tests to run in both linux/amd64 and linux/arm64.
Before this fix, I would get `SKIPPED` tests when testing on linux/arm64 and now all the tests run.
I've also noticed that the locks were not updated and would produce side-effects so I've added a separate `chore` commit to make sure there's "no noise" in the commit and/or when running the tests or other code in the repo.

fix: target_compatible_with excluding arm64

---

apt/private/deb_import.bzl

When a Debian package has a data file that's already compressed with `gzip` and named `data.tar.gz` it fails with:
```
Error in genrule: rule 'data' has file 'data.tar.gz' as both an input and an output.
```
See issue #98

fix: Debian packages with tar.gz data file

---

distroless/private/cacerts.bzl
docs/rules.md
examples/debian_snapshot/BUILD.bazel
examples/debian_snapshot/test_linux_amd64.yaml
examples/debian_snapshot/test_linux_arm64.yaml

Document that the `SSL_CERT_FILE` environment variable is required when using `cacerts()` as discussed in [PR71](https://github.com/GoogleContainerTools/rules_distroless/pull/71)

document that `cacerts()` requires `SSL_CERT_FILE` set in the environment

---

distroless/private/cacerts.bzl
distroless/private/flatten.bzl
distroless/private/group.bzl
distroless/private/home.bzl
distroless/private/locale.sh
distroless/private/os_release.bzl
distroless/private/passwd.bzl
distroless/private/tar.bzl

We weren't passing the flag to make gzip hermetic. Without the flag to
ignore timestamp, the shasum will differ based on the system time.
Also, DEFAULT_ARGS contained "--options=gzip:...", which is invalid when
using any other compression scheme. Therefore, remove that option from
DEFAULT_ARGS and provide an alternate function called
`add_default_compression_args` to add per-compression type default
arguments which can do things like make the compression more hermetic.
Repro instructions:
```
bazel test //...
find -L bazel-bin -name "*.gz" -exec sha256sum {} \; > sha
bazel clean --expunge
bazel test //...
sha256sum -c sha
```
Before, the above test would fail with sha256sum mismatches. With this patch, all shasums match.

tar: Make all gzip compression hermetic

---

WORKSPACE.bazel
apt/tests/BUILD.bazel
apt/tests/package_resolution_test.bzl
apt/tests/version_test.bzl
e2e/smoke/BUILD
e2e/smoke/WORKSPACE.bazel
examples/debian_snapshot/BUILD.bazel
examples/debian_snapshot/bullseye.lock.json
examples/debian_snapshot/bullseye.yaml
examples/debian_snapshot/bullseye_nolock.yaml

> [!NOTE]  
>  Stacked on top of #88 
* make apt/tests more readable by factoring out the parameters
* add a "test suite macro" in each test file that group all of the unit tests in the file and prepends a "test suite prefix". IMHO this is  better than using `unittest.suite` because we provide better naming than the automated `_test<NUMBER>` plus these better names are actual targets that can be executed one-by-one by name.
Add other nolock tests to exercise the package repos (the templates, etc).

refactor: testing

---

apt/private/BUILD.bazel

45509b0 added `version_constraint` to `apt_deb_repository.bzl` dependencies but it was missing from its `bzl_library` `deps`.

fix: apt_deb_repository bzl_library missing dep

---

apt/private/apt_deb_repository.bzl

* Resolves https://github.com/GoogleContainerTools/rules_distroless/issues/116
We have to download a package from https://apt-archive.postgresql.org/pub/repos/apt/dists/bookworm-pgdg-archive/main/binary-arm64/index.html, which only provides `Packages.bz2` and does not provide `Packages.xz` or `Packages.gz`.
We fixed this by locally patching our copy of `rules_distroless` to include `bz2` support here. This PR upstreams the change we made.

feat: Add bzip2 support to `apt_deb_repository.bzl`

---

distroless/private/flatten.sh
distroless/tests/asserts.bzl
examples/cacerts/BUILD.bazel
examples/flatten/BUILD.bazel
examples/group/BUILD.bazel
examples/home/BUILD.bazel
examples/java_keystore/BUILD.bazel
examples/locale/BUILD.bazel
examples/os_release/BUILD.bazel
examples/passwd/BUILD.bazel
examples/statusd/BUILD.bazel

#119 added a deduplicate option to `flatten` to address "duplicates of file paths not supported" errors when loading flattened images with Docker.
This option deduplicates directories, but in its current implementation it does not deduplicate files. This means the duplicate file path errors can still occur in some cases.
This change updates `flatten.sh` to deduplicate files as well, with the final file in the archive being preserved for each path.
It also renames `assert_tar_listing` to `assert_tar_mtree` and creates a new `assert_tar_listing` rule that lists archive contents instead of exporting an mtree.

feat: update flatten to deduplicate files

---

distroless/private/locale.sh
examples/locale/BUILD.bazel

Fixes #110
The locale rule has a time argument that wasn't being used in the locale.sh script.
Fix plus test exercising it.
Credit to @j-eid for finding the issue and proposing the fix!

fix: locale time override

---

apt/private/apt_deb_repository.bzl

Whilst `dict` ordering should preserve import order when iterated over keys, it looks like potentially `.items()` does not preserve insertion order. I can't reliably reproduce (assuming some non determinism is involved) but have examples such as the following:
```
bazel run @bookworm//:lock
WARNING: Download from https://snapshot-cloudflare.debian.org/archive/debian/20241221T204840Z/dists/bookworm/main/binary-amd64/Packages failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://snapshot-cloudflare.debian.org/archive/debian-security/20241221T204840Z/dists/bookworm-security/main/binary-amd64/Packages failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from …
```

Fix package index ordering

---

apt/tests/resolution/clang.yaml

9a7d2e8 added a manifest for clang with only amd64 and the @clang//clang target fails to build in arm64.

fix: #137 breaks tests in arm64

---

examples/debian_snapshot/BUILD.bazel
examples/ubuntu_snapshot/BUILD.bazel

Bazel was throwing an error when running the tests in MacOS even when the Linux tests were guarded with a target_compatible_with that was restricted to Linux.
As far as I could tell, this was because running `bazel test` with `//...` was recursively evaluating other targets like `//examples/ubuntu_snapshot:_noble_index_json` from `oci_image` and `oci_load`. When I guard those rules with a target_compatible_with everything works.
Also, seeing that e5f7dc0 also manually commented a test to fix CI for macos so I guess #120 didn't break this, it was probably happening since #115 added the new convenience targets.
Finally, maybe this is something that should be fixed in `rules_oci`, the "inner targets" that it creates should probably be restricted to only run in the `os` and `architecture` …

fix: #120 (and #115?) in MacOS

---

apt/private/deb_import.bzl

Fixes #141
In #99 I added a dependency to basename when it's not really needed.
Credit and thanks to @birunts for finding the issue and providing the solution!

fix: remove unnecessary basename

---

.pre-commit-config.yaml
README.md

Steps:
* `pre-commit migrate-config`
* `pre-commit autoupdate`
Then moving prettier from `v4.0.0-alpha.8` to the latest stable version in the mirror, `v3.1.0`, because the alpha versions seem to produce a node_modules directory somehow.
Note that the prettier mirror repo is archived, it seems unsupported / unmaintained since Dec 2023 :-/
The pre-commit run --all-files that I did and rebased into #120 broke the README :(
dadc64c added some of the fixes and this commit adds the CAUTION warning plus a TIP warning to highlight the need of small and readable PRs.
Now, prettier runs without breaking this Markdown.

fix: pre-commit run config and broken README

---

apt/extensions.bzl
apt/private/apt_deb_repository.bzl
apt/private/deb_resolve.bzl
apt/private/deb_translate_lock.bzl
apt/private/lockfile.bzl
e2e/smoke/bullseye.lock.json
e2e/smoke/bullseye.yaml
examples/debian_snapshot/bullseye.lock.json
examples/debian_snapshot/bullseye.yaml

Fixes #113
The Debian snapshot mirror fails quite often and, while the Cloudflare mirror has had some issues in the past (e.g. it was lagging replication for months) it's much more reliable.
This commit adds support for multiple URLs in the manifest. See examples/debian_snapshot/bullseye.yaml for a sample usage.

feat: support multiple URLs in sources

---

apt/private/apt_deb_repository.bzl
apt/private/apt_dep_resolver.bzl
apt/tests/resolution_test.bzl

Currently, a simple install of `bash` produces the following error:
```
WARNING: Following dependencies could not be resolved for bash: awk
```
In identifying the root cause of this issue, found a few behaviors for the `Provides` key are not correct (as described [by the spec here](https://www.debian.org/doc/debian-policy/ch-relationships.html#virtual-packages-provides)).
Fixed the following in `Provides`:
* Handle multiple packages, i.e. `Provides: bar, baz`.
* Handle unversioned packages, i.e. `Provides: bar` and `Provides: bar (= 1.0)` are both valid.
* Ensure alternatives (referred in code as dependency groups) are evaluated left-to-right and added to unmet_deps if none resolve.
* Handle multiple candidates for virtual packages if can fallback to a single `Priority: required` package. …

Fix virtual package resolution

---

MODULE.bazel
apt/BUILD.bazel
apt/extensions.bzl

When using a lockfile, an entry in the MODULE.bazel.lock is redundant.
Marking the extension as reproducible only when a lockfile is provided saves an entry in the lockfile.
Note, I had to move `bazel_features` out of `dev_dependency` because the `reproducible` field on `extension_metadata` only appeared in `7.1.0`.

fix: mark apt extension as reproducible when using a lockfile

---

distroless/private/cacerts.sh

There are few _non hermetic_ tools used across the project.
Some of them are handled with #140 
This PR is to remove some usage of local `ls` & `cat` tools in shell script.

chore: improve hermeticity

---

apt/private/apt_dep_resolver.bzl
apt/tests/resolution_test.bzl

Prevent adding root package as a dependency to itself.
Resolves #128 & Closes #128.

fix: circular dependencies

---

MODULE.bazel
distroless/private/flatten.bzl
distroless/private/group.bzl
distroless/private/home.bzl
distroless/private/os_release.bzl
distroless/private/passwd.bzl
distroless/private/tar.bzl

Upgrade `aspect_bazel_lib` from 2.9.4 to 2.14.0, and stop setting `--options=gzip:!timestamp` as an argument when running `tar`.
The tar lib in `aspect_bazel_lib` >2.10.0 already sets this argument, so setting it again causes warnings like these:
```
INFO: From Tar examples/passwd/passwd.tar.gz:
tar: Ignoring previous option 'gzip:!timestamp,', separate multiple options with commas
INFO: From Tar examples/ubuntu_snapshot/group.tar.gz:
tar: Ignoring previous option 'gzip:!timestamp,', separate multiple options with commas
```

Upgrade `aspect_bazel_lib` to 2.14.0

---

distroless/toolchains.bzl

Per `MODULE.bazel`, this repo assumes `rules_java` 8.8.0 or better. However, under `rules_java` 8.8.0, the `rules_java_dependencies()` in `@rules_java//java:repositories.bzl` is a stub that prints a message telling people to load the routine from its new location in `@rules_java//java:rules_java_deps.bzl`.

Use the correct rules_java_dependencies() for rules_java 8.8.0.

---

README.md

When going through the documentation to add `rules_distroless` to Bzlmod, I received an error issued by Bazel formatter that the previous version was not available on Bazel Container Registry.
Updated the README with the latest release and bumped the git commit sha to the latest on this repo.

Update README.md with a version that exists in BCR
